"""empty message

Revision ID: 97be9b4ff269
Revises: fffc2c9b09b8
Create Date: 2019-12-23 17:10:25.023457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97be9b4ff269'
down_revision = 'fffc2c9b09b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed_list', sa.Boolean(), nullable=True))
    op.add_column('todolists', sa.Column('list_name', sa.String(), nullable=False))
    op.drop_column('todolists', 'name')
    op.drop_column('todolists', 'completed')
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'completed_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed_list', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'completed')
    op.add_column('todolists', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('todolists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todolists', 'list_name')
    op.drop_column('todolists', 'completed_list')
    # ### end Alembic commands ###
