"""empty message

Revision ID: d11910464998
Revises: 97be9b4ff269
Create Date: 2020-03-24 14:31:10.345736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11910464998'
down_revision = '97be9b4ff269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('todolists', 'completed_list')
    op.drop_column('todolists', 'list_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('list_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('todolists', sa.Column('completed_list', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todolists', 'name')
    # ### end Alembic commands ###
