"""empty message

Revision ID: fffc2c9b09b8
Revises: e6f34092e46a
Create Date: 2019-12-23 17:08:38.256600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffc2c9b09b8'
down_revision = 'e6f34092e46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed_list', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'completed_list')
    # ### end Alembic commands ###
